### ISSUE TITLE
Составить ТЗ на сайт

### ISSUE THREAD

**Issue by alexbaumgertner** [piterjs/piterjs.org.0#8]
Репозиторий:
https://github.com/piterjs/community-site

Примерный стек:
- nodejs
- koa2
- mongo
- React/Redux

## Примеры
- http://yarfrontend.ru
-  http://kyivjs.org
- https://bem.info :trollface:

**Comment by alexbaumgertner** [comment]
Ключевые разделы:
- расписание встреч (архив, расписание будущих встреч)
- форма подачи доклада
- агрегатор новостей с социальных сетей (?)
- форум (?)
- страница о проекте (+ об участниках)
- страница проектов (?) например, open source платформа сообщества

**Comment by amarchen** [comment]
**Основная цель всего PiterJS движения (ИМХО)**
- Способствовать развитию комьюнити, работающих с JS в Петербурге и за пределами
  - В данный момент прежде всего посредством митапов

Для кого сайт (ИМХО):
- В первую очередь - для посетителей митапов
- Во вторую - для потенциальных докладчиков
- В третью - для случайно забредших людей, которым возможно интересна тема

Цели для этих групп (ИМХО):
**А. Для посетителей митапов**

1. Информирование о том, где получить свежую дозу митапа

- Сразу видеть, когда ближайший и почему он крут-полезен (общая тема, список докладов, ссылки на профили докладчиков и их предыдущие доклады, возможно и на других площадках - лишь бы было можно оценить интересность докладчика и темы)

- кнопки подписки на уведомления именно о новых метанах (возможно даже вообще без других новостей) в любой удобной форме: телеграм, твиттер, обязательно e-mail рассылка (возможно даже отдельная “только уведомления и митапах и вообще никакого спама!”)

- Информация о том, где обсудить стоит ли идти на митап.
Более широкий список рассылки? Определённая ветка форума? Канал в телеграме-слаке-IRC?

2. Канал для общения о просто JS

**B. Для потенциальных докладчиков**
1. Способ подать!
- Лёгкий способ подать тему. Так же как на meetabit, наверное

2. Узнать, что интересно людям AKA подталкивание потенциальных докладчиков к тому, чтобы они стали докладчиками
- Список потенциальных тем для митапов в будущем? С комментами-предложениями?
- Ветка форума или чат или список рассылки для обсуждения потенциально интересных тем? 
- Demo/featured video с докладом или slideset?

**C. Для случайно забредших людей**
1. Да всё то же самое + может быть живой twitter feed

ИМХО: Приоритеты примерно следующие:
A1, B1, A2, C1

**Comment by alexbaumgertner** [comment]
Спасибо большое за развернутый комментарий!

В первом приоритете получается календарь-расписание встреч с архивом, подпиской на будущие события и обсуждением.

**Comment by amarchen** [comment]
Хотел бы уточнить, что мой коммент - это ИМХО, причём написанное без длительных обдумываний. Я не готов "на самом деле работать" над этим, только комментирую и совсем не против, если коммент будет полностью проигнорирован. Даже если бы он был совсем неплох - важнее то, что собственно делающие люди готовы сделать :)

**Comment by mike1pol** [comment]
Надо не забыть, про интеграции с сервисами по типу Meetabit и Timepad
